
import path from 'node:path';

export const BASE_DIR = path.resolve(__dirname, '../..');

const LOG_DIR_NAME = 'logs';
export const LOG_DIR_PATH = [
  BASE_DIR,
  LOG_DIR_NAME,
].join(path.sep);
export const APP_LOGGER_NAME = 'app';
export const LOG_FILE_EXT = 'log';

/* pre-build assets, e.g. mime-db extension map generated by scripts _*/
const external_dir_name = 'extern';
export const extern_dir_path = [
  BASE_DIR,
  external_dir_name,
].join(path.sep);
export const mime_gen_meta_file_name = 'mime-gen-meta.json';

/* temp dir for running scripts _*/
const external_temp_dir_name = 'extern-tmp';
export const external_temp_dir_path = [
  BASE_DIR,
  external_temp_dir_name,
].join(path.sep);

/* dev, cache */
const jcd_cache_dir_name = '_jcd_cache';
export const jcd_cache_dir_path = [
  BASE_DIR,
  jcd_cache_dir_name,
].join(path.sep);
